// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnM63ri1NbIE4tJH3HRihH0gZVm3_k2q8',
    appId: '1:37746091766:web:29484d18cd5c7874346ed7',
    messagingSenderId: '37746091766',
    projectId: 'mymate-62700',
    authDomain: 'mymate-62700.firebaseapp.com',
    databaseURL: 'https://mymate-62700-default-rtdb.firebaseio.com',
    storageBucket: 'mymate-62700.firebasestorage.app',
    measurementId: 'G-SP293DNRH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufh3akz6SqAq88FWaKZe22-3wx5n3vp0',
    appId: '1:37746091766:android:4fc876ddf4340042346ed7',
    messagingSenderId: '37746091766',
    projectId: 'mymate-62700',
    databaseURL: 'https://mymate-62700-default-rtdb.firebaseio.com',
    storageBucket: 'mymate-62700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCrFyHndzEdDyrfboYmnM1ffKAy3OOxNk',
    appId: '1:37746091766:ios:7c530ff9b1724b47346ed7',
    messagingSenderId: '37746091766',
    projectId: 'mymate-62700',
    databaseURL: 'https://mymate-62700-default-rtdb.firebaseio.com',
    storageBucket: 'mymate-62700.firebasestorage.app',
    iosBundleId: 'com.example.dashboardMyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCrFyHndzEdDyrfboYmnM1ffKAy3OOxNk',
    appId: '1:37746091766:ios:7c530ff9b1724b47346ed7',
    messagingSenderId: '37746091766',
    projectId: 'mymate-62700',
    databaseURL: 'https://mymate-62700-default-rtdb.firebaseio.com',
    storageBucket: 'mymate-62700.firebasestorage.app',
    iosBundleId: 'com.example.dashboardMyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnM63ri1NbIE4tJH3HRihH0gZVm3_k2q8',
    appId: '1:37746091766:web:5568147be5116295346ed7',
    messagingSenderId: '37746091766',
    projectId: 'mymate-62700',
    authDomain: 'mymate-62700.firebaseapp.com',
    databaseURL: 'https://mymate-62700-default-rtdb.firebaseio.com',
    storageBucket: 'mymate-62700.firebasestorage.app',
    measurementId: 'G-LPBYV03TX8',
  );
}
